groups:
  - name: node_alerts
    rules:
      - alert: Node DOWN
        expr: changes(up[5m]) > 0 and up == 0
        for: 1m
        labels:
          severity: warning
          resolve_automatically: true
        annotations:
          title: Node {{ $labels.instance }} is down
          description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 2 minutes. Node seems down.
      - alert: Hight CPU
        expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance)) * 100 > 70
        for: 1m
        labels:
          severity: warning
          resolve_automatically: true
        annotations:
          summary: Hight CPU usage for  {{ $labels.instance }}
          description: The target {{ $labels.instance }} is using {{ $value }}% CPU
      - alert: Disk Out Of Space
        expr: 100 - (100 * sum(node_filesystem_avail_bytes{mountpoint="/"}) by (instance) / sum(node_filesystem_size_bytes{mountpoint="/"}) by (instance)) > 80
        for: 1m
        labels:
          severity: warning
          resolve_automatically: true
        annotations:
          summary: Disk Out Of Space for  {{ $labels.instance }}
          description: The target {{ $labels.instance }} has {{ $value }}% Used Storage
  - name: cadvisor
    rules:
      - alert: Container killed
        expr: time() - container_last_seen{image!=""} > 60
        labels:
          severity: warning
          resolve_automatically: false
        annotations:
          summary: Container killed for  {{ $labels.instance }}
          description: The container "{{ $labels.image }}" for the target {{ $labels.instance }} is out of service
