global:
  scrape_interval:     15s
  evaluation_interval: 15s


  external_labels:
      monitor: 'docker-host-alpha'

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
        - "nodeexporter:9100"
        - "192.168.1.100:9100"

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets:
        - "cadvisor:8080"
        - "192.168.1.100:8000"

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: 
        - "pushgateway:9091"
        - "192.168.1.100:9091"
